### ISSUE TITLE
Request - New Shortcode to Hide "Download"

### ISSUE THREAD

**Issue by tardis221** [ErinMorelli/dlm-changelog#2]
Would be possible to add another shortcode option? The option I am looking for is to hide the "download" link.

**Comment by ErinMorelli** [comment]
This is a great suggestion! I'll add the option in the next update. In the mean time, if you still need to hide the link, you can target it with CSS using `.dlm-changelog-item .cl-dl a`

**Comment by ErinMorelli** [comment]
This feature is now available in v1.2.0! Use the `hide_links` option in your shortcode, like this:

`[dlm_changelog id={DLM Download ID} hide_links="1"]`

You can also hide the download's release date like this:

``[dlm_changelog id={DLM Download ID} hide_release="1"]`

Or use both together to hide that line of extra info all together:

``[dlm_changelog id={DLM Download ID} hide_links="1" hide_release="1"]`

Let me know what you think or if you run into any issues!
